package edu.nk.pker.model.po;

// Generated 2015-5-20 10:08:13 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Choice generated by hbm2java
 */
@Entity
@Table(name = "choice", catalog = "pker")
public class Choice implements java.io.Serializable {

	private Integer optionId;
	private int questionId;
	private Integer optionOrder;
	private String optionContent;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<Record> records = new HashSet<Record>(0);

	public Choice() {
	}

	public Choice(int questionId, String optionContent) {
		this.questionId = questionId;
		this.optionContent = optionContent;
	}

	public Choice(int questionId, Integer optionOrder, String optionContent,
			Set<Question> questions, Set<Record> records) {
		this.questionId = questionId;
		this.optionOrder = optionOrder;
		this.optionContent = optionContent;
		this.questions = questions;
		this.records = records;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "option_id", unique = true, nullable = false)
	public Integer getOptionId() {
		return this.optionId;
	}

	public void setOptionId(Integer optionId) {
		this.optionId = optionId;
	}

	@Column(name = "question_id", nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	@Column(name = "option_order")
	public Integer getOptionOrder() {
		return this.optionOrder;
	}

	public void setOptionOrder(Integer optionOrder) {
		this.optionOrder = optionOrder;
	}

	@Column(name = "option_content", nullable = false, length = 65535)
	public String getOptionContent() {
		return this.optionContent;
	}

	public void setOptionContent(String optionContent) {
		this.optionContent = optionContent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "choice")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "choice")
	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

}
