package edu.nk.pker.model.po;

// Generated 2015-5-20 10:08:13 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Competition generated by hbm2java
 */
@Entity
@Table(name = "competition", catalog = "pker")
public class Competition implements java.io.Serializable {

	private Integer competitionId;
	private Paper paper;
	private User user;
	private Integer pktype;
	private Date createTime;
	private Date updateTime;
	private Set<CompetitionUser> competitionUsers = new HashSet<CompetitionUser>(
			0);

	public Competition() {
	}

	public Competition(Paper paper, User user, Date createTime, Date updateTime) {
		this.paper = paper;
		this.user = user;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Competition(Paper paper, User user, Integer pktype, Date createTime,
			Date updateTime, Set<CompetitionUser> competitionUsers) {
		this.paper = paper;
		this.user = user;
		this.pktype = pktype;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.competitionUsers = competitionUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "competition_id", unique = true, nullable = false)
	public Integer getCompetitionId() {
		return this.competitionId;
	}

	public void setCompetitionId(Integer competitionId) {
		this.competitionId = competitionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paper_id", nullable = false)
	public Paper getPaper() {
		return this.paper;
	}

	public void setPaper(Paper paper) {
		this.paper = paper;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "pktype")
	public Integer getPktype() {
		return this.pktype;
	}

	public void setPktype(Integer pktype) {
		this.pktype = pktype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competition")
	public Set<CompetitionUser> getCompetitionUsers() {
		return this.competitionUsers;
	}

	public void setCompetitionUsers(Set<CompetitionUser> competitionUsers) {
		this.competitionUsers = competitionUsers;
	}

}
