package edu.nk.pker.model.po;

// Generated 2015-5-20 10:08:13 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "pker")
public class Message implements java.io.Serializable {

	private Integer msgid;
	private User userBySenderId;
	private User userByReceiverId;
	private Date createTime;
	private Boolean isRead;
	private Date receiveTime;
	private String msgcontent;

	public Message() {
	}

	public Message(User userBySenderId, User userByReceiverId, Date createTime,
			Date receiveTime, String msgcontent) {
		this.userBySenderId = userBySenderId;
		this.userByReceiverId = userByReceiverId;
		this.createTime = createTime;
		this.receiveTime = receiveTime;
		this.msgcontent = msgcontent;
	}

	public Message(User userBySenderId, User userByReceiverId, Date createTime,
			Boolean isRead, Date receiveTime, String msgcontent) {
		this.userBySenderId = userBySenderId;
		this.userByReceiverId = userByReceiverId;
		this.createTime = createTime;
		this.isRead = isRead;
		this.receiveTime = receiveTime;
		this.msgcontent = msgcontent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "msgid", unique = true, nullable = false)
	public Integer getMsgid() {
		return this.msgid;
	}

	public void setMsgid(Integer msgid) {
		this.msgid = msgid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender_id", nullable = false)
	public User getUserBySenderId() {
		return this.userBySenderId;
	}

	public void setUserBySenderId(User userBySenderId) {
		this.userBySenderId = userBySenderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "receiver_id", nullable = false)
	public User getUserByReceiverId() {
		return this.userByReceiverId;
	}

	public void setUserByReceiverId(User userByReceiverId) {
		this.userByReceiverId = userByReceiverId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "is_read")
	public Boolean getIsRead() {
		return this.isRead;
	}

	public void setIsRead(Boolean isRead) {
		this.isRead = isRead;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "receive_time", nullable = false, length = 19)
	public Date getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	@Column(name = "msgcontent", nullable = false, length = 65535)
	public String getMsgcontent() {
		return this.msgcontent;
	}

	public void setMsgcontent(String msgcontent) {
		this.msgcontent = msgcontent;
	}

}
