package edu.nk.pker.model.po;

// Generated 2015-5-20 10:08:13 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionTag generated by hbm2java
 */
@Entity
@Table(name = "question_tag", catalog = "pker")
public class QuestionTag implements java.io.Serializable {

	private Integer questionTagId;
	private Question question;
	private Tag tag;
	private Date createTime;
	private String creator;

	public QuestionTag() {
	}

	public QuestionTag(Question question, Tag tag, Date createTime) {
		this.question = question;
		this.tag = tag;
		this.createTime = createTime;
	}

	public QuestionTag(Question question, Tag tag, Date createTime,
			String creator) {
		this.question = question;
		this.tag = tag;
		this.createTime = createTime;
		this.creator = creator;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "question_tag_id", unique = true, nullable = false)
	public Integer getQuestionTagId() {
		return this.questionTagId;
	}

	public void setQuestionTagId(Integer questionTagId) {
		this.questionTagId = questionTagId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tag_id", nullable = false)
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "creator", length = 100)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

}
