package edu.nk.pker.model.po;

// Generated 2015-6-21 22:47:36 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private Integer questionId;
	private Category category;
	private QuestionType questionType;
	private User user;
	private String name;
	private String answer;
	private String content;
	private String reference;
	private String options;
	private String analysis;
	private String appendix;
	private Date createTime;
	private Date lastModify;
	private Integer rightTimes;
	private Integer exposeTimes;
	private Integer wrongTimes;
	private Integer difficulty;
	private Set questionTags = new HashSet(0);
	private Set records = new HashSet(0);
	private Set favorites = new HashSet(0);
	private Set comments = new HashSet(0);
	private Set notes = new HashSet(0);

	public Question() {
	}

	public Question(String name, String content, Date createTime,
			Date lastModify) {
		this.name = name;
		this.content = content;
		this.createTime = createTime;
		this.lastModify = lastModify;
	}

	public Question(Category category, QuestionType questionType, User user,
			String name, String answer, String content, String reference,
			String options, String analysis, String appendix, Date createTime,
			Date lastModify, Integer rightTimes, Integer exposeTimes,
			Integer wrongTimes, Integer difficulty, Set questionTags,
			Set records, Set favorites, Set comments, Set notes) {
		this.category = category;
		this.questionType = questionType;
		this.user = user;
		this.name = name;
		this.answer = answer;
		this.content = content;
		this.reference = reference;
		this.options = options;
		this.analysis = analysis;
		this.appendix = appendix;
		this.createTime = createTime;
		this.lastModify = lastModify;
		this.rightTimes = rightTimes;
		this.exposeTimes = exposeTimes;
		this.wrongTimes = wrongTimes;
		this.difficulty = difficulty;
		this.questionTags = questionTags;
		this.records = records;
		this.favorites = favorites;
		this.comments = comments;
		this.notes = notes;
	}

	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public QuestionType getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(QuestionType questionType) {
		this.questionType = questionType;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getOptions() {
		return this.options;
	}

	public void setOptions(String options) {
		this.options = options;
	}

	public String getAnalysis() {
		return this.analysis;
	}

	public void setAnalysis(String analysis) {
		this.analysis = analysis;
	}

	public String getAppendix() {
		return this.appendix;
	}

	public void setAppendix(String appendix) {
		this.appendix = appendix;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLastModify() {
		return this.lastModify;
	}

	public void setLastModify(Date lastModify) {
		this.lastModify = lastModify;
	}

	public Integer getRightTimes() {
		return this.rightTimes;
	}

	public void setRightTimes(Integer rightTimes) {
		this.rightTimes = rightTimes;
	}

	public Integer getExposeTimes() {
		return this.exposeTimes;
	}

	public void setExposeTimes(Integer exposeTimes) {
		this.exposeTimes = exposeTimes;
	}

	public Integer getWrongTimes() {
		return this.wrongTimes;
	}

	public void setWrongTimes(Integer wrongTimes) {
		this.wrongTimes = wrongTimes;
	}

	public Integer getDifficulty() {
		return this.difficulty;
	}

	public void setDifficulty(Integer difficulty) {
		this.difficulty = difficulty;
	}

	public Set getQuestionTags() {
		return this.questionTags;
	}

	public void setQuestionTags(Set questionTags) {
		this.questionTags = questionTags;
	}

	public Set getRecords() {
		return this.records;
	}

	public void setRecords(Set records) {
		this.records = records;
	}

	public Set getFavorites() {
		return this.favorites;
	}

	public void setFavorites(Set favorites) {
		this.favorites = favorites;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getNotes() {
		return this.notes;
	}

	public void setNotes(Set notes) {
		this.notes = notes;
	}

}
