package edu.nk.pker.model.po;

// Generated 2015-5-20 10:08:13 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QuestionType generated by hbm2java
 */
@Entity
@Table(name = "question_type", catalog = "pker")
public class QuestionType implements java.io.Serializable {

	private Integer id;
	private String name;
	private boolean subjective;
	private Set<Question> questions = new HashSet<Question>(0);

	public QuestionType() {
	}

	public QuestionType(String name, boolean subjective) {
		this.name = name;
		this.subjective = subjective;
	}

	public QuestionType(String name, boolean subjective, Set<Question> questions) {
		this.name = name;
		this.subjective = subjective;
		this.questions = questions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "subjective", nullable = false)
	public boolean isSubjective() {
		return this.subjective;
	}

	public void setSubjective(boolean subjective) {
		this.subjective = subjective;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questionType")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
